/**
 * MysticFate - Google Play 合规模块
 * Google Play Compliance Module
 * 
 * 功能：
 * 1. 娱乐免责声明
 * 2. 隐私政策
 * 3. 年龄确认
 * 4. 付费透明度
 */

// ==================== 合规文本 ====================

const COMPLIANCE_TEXTS = {
  // 娱乐免责声明
  disclaimer: {
    title: 'Entertainment Purposes Only',
    short: 'For entertainment purposes only.',
    full: `This app is intended for entertainment purposes only. All readings, interpretations, and predictions generated by this app are based on traditional Chinese astrological principles and AI-generated content. They should not be considered as professional medical, financial, legal, or any other professional advice.

The content provided by Mystic Fate is for entertainment and self-reflection purposes only. While we strive to provide accurate and meaningful content, we make no guarantees about the completeness, reliability, or accuracy of any information or predictions.

By using this app, you acknowledge and agree that:
1. All content is for entertainment purposes only
2. No decisions should be made based solely on the app's content
3. The app does not replace professional advice of any kind
4. Individual results may vary and are not guaranteed

「本应用仅供娱乐目的使用。所有解读和建议不应被视为专业意见。」`
  },

  // 隐私政策摘要
  privacySummary: {
    title: 'Privacy Policy Summary',
    sections: [
      {
        heading: 'Information We Collect',
        content: `We collect minimal personal information to provide our services:
• Birth date and time (for astrological calculations)
• Name (for personalized readings)
• Usage data (for improving our service)

We do NOT collect:
• Location data
• Contact information (unless you voluntarily provide it)
• Financial information (processed by Google Play)
`
      },
      {
        heading: 'How We Use Your Data',
        content: `• Generate personalized astrological readings
• Store your chart data securely
• Improve our AI-powered predictions
• Send optional daily notifications

Your data is encrypted and stored securely. We never sell your personal information to third parties.`
      },
      {
        heading: 'Your Rights',
        content: `You have the right to:
• Access your stored data
• Delete your account and data
• Opt out of notifications
• Export your data

Contact us at privacy@mysticfate.app for any privacy-related requests.`
      }
    ]
  },

  // 付费说明
  paymentInfo: {
    title: 'Payment Information',
    creditPackages: [
      { name: 'Starter', credits: 30, price: '$1.99', perCredit: '$0.066' },
      { name: 'Popular', credits: 100, price: '$4.99', perCredit: '$0.050', popular: true },
      { name: 'Premium', credits: 250, price: '$9.99', perCredit: '$0.040' }
    ],
    subscription: {
      name: 'Pro Subscription',
      price: '$14.99/month',
      features: [
        'Unlimited AI readings',
        'Daily personalized whispers',
        'Priority support',
        'Exclusive features'
      ]
    },
    refundPolicy: `Refund Policy:
• Google Play purchases are subject to Google Play's refund policies
• Unused Credits may be eligible for refund within 14 days of purchase
• Contact support@mysticfate.app for refund requests`
  },

  // 年龄要求
  ageRequirement: {
    minimum: 13,
    statement: 'This app is intended for users aged 13 and older.',
    warning: 'If you are under 13, please do not use this app without parental consent.'
  },

  // 数据安全
  dataSecurity: {
    encryption: 'All personal data is encrypted using industry-standard encryption.',
    storage: 'Data is stored securely in compliance with Google Play requirements.',
    sharing: 'We do not share your personal data with third parties for marketing purposes.'
  }
};

// ==================== UI组件 ====================

/**
 * 显示免责声明弹窗
 */
function showDisclaimerModal() {
  const modal = document.createElement('div');
  modal.id = 'disclaimer-modal';
  modal.className = 'compliance-modal';
  
  modal.innerHTML = `
    <div class="modal-overlay" onclick="closeDisclaimerModal()"></div>
    <div class="modal-content compliance-content">
      <div class="compliance-header">
        <div class="compliance-icon">⚠️</div>
        <h2>Entertainment Purposes Only</h2>
      </div>
      
      <div class="compliance-text">
        <p class="disclaimer-intro">Welcome to Mystic Fate!</p>
        <p class="disclaimer-text">${COMPLIANCE_TEXTS.disclaimer.full.split('\n\n')[0]}</p>
        
        <div class="key-points">
          <div class="point">
            <span class="point-icon">✦</span>
            <span>All readings are for entertainment only</span>
          </div>
          <div class="point">
            <span class="point-icon">✦</span>
            <span>Not a substitute for professional advice</span>
          </div>
          <div class="point">
            <span class="point-icon">✦</span>
            <span>Individual results may vary</span>
          </div>
        </div>
        
        <div class="zh-text">
          <p>「本应用仅供娱乐目的使用」</p>
        </div>
      </div>
      
      <div class="compliance-actions">
        <button class="compliance-btn primary" onclick="acceptDisclaimer()">
          I Understand & Continue
        </button>
      </div>
      
      <div class="compliance-footer">
        <p>By continuing, you agree to our <a href="#" onclick="showPrivacyPolicy()">Privacy Policy</a> and <a href="#" onclick="showTermsOfService()">Terms of Service</a>.</p>
      </div>
    </div>
  `;
  
  document.body.appendChild(modal);
  
  // 添加样式
  addComplianceStyles();
}

/**
 * 显示隐私政策
 */
function showPrivacyPolicy() {
  const modal = document.createElement('div');
  modal.id = 'privacy-modal';
  modal.className = 'compliance-modal';
  
  const sectionsHTML = COMPLIANCE_TEXTS.privacySummary.sections.map(section => `
    <div class="privacy-section">
      <h3>${section.heading}</h3>
      <p>${section.content}</p>
    </div>
  `).join('');
  
  modal.innerHTML = `
    <div class="modal-overlay" onclick="closePrivacyModal()"></div>
    <div class="modal-content compliance-content privacy-content">
      <div class="compliance-header">
        <h2>Privacy Policy</h2>
        <button class="close-btn" onclick="closePrivacyModal()">×</button>
      </div>
      
      <div class="privacy-body">
        ${sectionsHTML}
        
        <div class="data-security">
          <h3>Data Security</h3>
          <p>${COMPLIANCE_TEXTS.dataSecurity.encryption}</p>
          <p>${COMPLIANCE_TEXTS.dataSecurity.storage}</p>
        </div>
      </div>
      
      <div class="compliance-actions">
        <button class="compliance-btn secondary" onclick="closePrivacyModal()">
          Close
        </button>
      </div>
    </div>
  `;
  
  document.body.appendChild(modal);
}

/**
 * 显示付费说明
 */
function showPaymentInfo() {
  const modal = document.createElement('div');
  modal.id = 'payment-modal';
  modal.className = 'compliance-modal';
  
  const packagesHTML = COMPLIANCE_TEXTS.paymentInfo.creditPackages.map(pkg => `
    <div class="package-card ${pkg.popular ? 'popular' : ''}">
      ${pkg.popular ? '<div class="popular-badge">Popular</div>' : ''}
      <div class="package-name">${pkg.name}</div>
      <div class="package-credits">${pkg.credits} Credits</div>
      <div class="package-price">${pkg.price}</div>
      <div class="package-per-credit">${pkg.perCredit}/credit</div>
    </div>
  `).join('');
  
  modal.innerHTML = `
    <div class="modal-overlay" onclick="closePaymentModal()"></div>
    <div class="modal-content compliance-content payment-content">
      <div class="compliance-header">
        <h2>Credits & Subscriptions</h2>
        <button class="close-btn" onclick="closePaymentModal()">×</button>
      </div>
      
      <div class="payment-section">
        <h3>Credit Packages</h3>
        <div class="packages-grid">
          ${packagesHTML}
        </div>
      </div>
      
      <div class="payment-section">
        <h3>Pro Subscription</h3>
        <div class="subscription-card">
          <div class="subscription-header">
            <span class="sub-name">${COMPLIANCE_TEXTS.paymentInfo.subscription.name}</span>
            <span class="sub-price">${COMPLIANCE_TEXTS.paymentInfo.subscription.price}</span>
          </div>
          <ul class="sub-features">
            ${COMPLIANCE_TEXTS.paymentInfo.subscription.features.map(f => `<li>✦ ${f}</li>`).join('')}
          </ul>
        </div>
      </div>
      
      <div class="payment-section">
        <h3>Refund Policy</h3>
        <p class="refund-text">${COMPLIANCE_TEXTS.paymentInfo.refundPolicy}</p>
      </div>
      
      <div class="compliance-actions">
        <button class="compliance-btn secondary" onclick="closePaymentModal()">
          Close
        </button>
      </div>
    </div>
  `;
  
  document.body.appendChild(modal);
}

/**
 * 显示年龄确认
 */
function showAgeConfirmation() {
  const modal = document.createElement('div');
  modal.id = 'age-modal';
  modal.className = 'compliance-modal';
  
  modal.innerHTML = `
    <div class="modal-overlay"></div>
    <div class="modal-content compliance-content age-content">
      <div class="compliance-header">
        <div class="compliance-icon">✦</div>
        <h2>Age Verification</h2>
      </div>
      
      <div class="age-text">
        <p>${COMPLIANCE_TEXTS.ageRequirement.statement}</p>
        <p class="age-warning">${COMPLIANCE_TEXTS.ageRequirement.warning}</p>
      </div>
      
      <div class="compliance-actions">
        <button class="compliance-btn primary" onclick="confirmAge()">
          I am 13 or older
        </button>
        <button class="compliance-btn secondary" onclick="declineAge()">
          I am under 13
        </button>
      </div>
    </div>
  `;
  
  document.body.appendChild(modal);
}

// ==================== 辅助函数 ====================

function closeDisclaimerModal() {
  const modal = document.getElementById('disclaimer-modal');
  if (modal) modal.remove();
}

function closePrivacyModal() {
  const modal = document.getElementById('privacy-modal');
  if (modal) modal.remove();
}

function closePaymentModal() {
  const modal = document.getElementById('payment-modal');
  if (modal) modal.remove();
}

function acceptDisclaimer() {
  localStorage.setItem('disclaimer_accepted', 'true');
  localStorage.setItem('disclaimer_date', new Date().toISOString());
  closeDisclaimerModal();
  
  // 继续到下一个屏幕
  if (typeof showScreen === 'function') {
    showScreen('birthdate-screen');
  }
}

function confirmAge() {
  localStorage.setItem('age_verified', 'true');
  const modal = document.getElementById('age-modal');
  if (modal) modal.remove();
  showDisclaimerModal();
}

function declineAge() {
  const modal = document.getElementById('age-modal');
  if (modal) modal.remove();
  alert('Sorry, you must be 13 or older to use this app. Please ask a parent or guardian for assistance.');
  // 可以重定向到其他页面
}

/**
 * 检查是否需要显示免责声明
 */
function checkDisclaimerRequired() {
  const accepted = localStorage.getItem('disclaimer_accepted');
  if (!accepted) {
    showDisclaimerModal();
    return true;
  }
  return false;
}

/**
 * 获取合规信息（用于App描述等）
 */
function getComplianceInfo() {
  return {
    disclaimer: COMPLIANCE_TEXTS.disclaimer.short,
    privacySummary: 'We collect minimal data (birth info, name) for readings. Data is encrypted and never sold. Google Play Privacy Policy applies.',
    ageRating: 'PEGI 12 (due to mystical/occult themes)',
    contentRating: 'Everyone' // Google Play content rating
  };
}

// ==================== 样式 ====================

function addComplianceStyles() {
  if (document.getElementById('compliance-styles')) return;
  
  const styles = document.createElement('style');
  styles.id = 'compliance-styles';
  styles.textContent = `
    .compliance-modal {
      position: fixed;
      top: 0;
      left: 0;
      width: 100%;
      height: 100%;
      z-index: 10000;
      display: flex;
      align-items: center;
      justify-content: center;
    }
    
    .compliance-modal .modal-overlay {
      position: absolute;
      top: 0;
      left: 0;
      width: 100%;
      height: 100%;
      background: rgba(0, 0, 0, 0.85);
    }
    
    .compliance-content {
      position: relative;
      max-width: 480px;
      width: 90%;
      max-height: 90vh;
      overflow-y: auto;
      background: #14141F;
      border: 1px solid #C9A96E;
      border-radius: 16px;
      padding: 32px 24px;
    }
    
    .compliance-header {
      text-align: center;
      margin-bottom: 24px;
    }
    
    .compliance-icon {
      font-size: 48px;
      margin-bottom: 12px;
    }
    
    .compliance-header h2 {
      font-family: 'Cinzel', serif;
      font-size: 1.5rem;
      color: #C9A96E;
      margin: 0;
    }
    
    .compliance-text {
      margin-bottom: 24px;
    }
    
    .disclaimer-intro {
      font-size: 1.1rem;
      color: #E8E4DF;
      margin-bottom: 16px;
    }
    
    .disclaimer-text {
      font-size: 0.9rem;
      color: #7A7572;
      line-height: 1.6;
      margin-bottom: 20px;
    }
    
    .key-points {
      background: rgba(201, 169, 110, 0.1);
      border-radius: 12px;
      padding: 16px;
      margin-bottom: 16px;
    }
    
    .key-points .point {
      display: flex;
      align-items: center;
      gap: 12px;
      padding: 8px 0;
      color: #E8E4DF;
      font-size: 0.9rem;
    }
    
    .key-points .point-icon {
      color: #C9A96E;
    }
    
    .zh-text {
      text-align: center;
      padding: 12px;
      border-top: 1px solid rgba(201, 169, 110, 0.2);
    }
    
    .zh-text p {
      font-size: 0.9rem;
      color: #8B7355;
      font-style: italic;
      margin: 0;
    }
    
    .compliance-actions {
      display: flex;
      flex-direction: column;
      gap: 12px;
    }
    
    .compliance-btn {
      width: 100%;
      padding: 14px 24px;
      border-radius: 12px;
      font-family: 'Cinzel', serif;
      font-size: 1rem;
      cursor: pointer;
      transition: all 0.3s;
    }
    
    .compliance-btn.primary {
      background: linear-gradient(135deg, #C9A96E 0%, #8B7355 100%);
      border: none;
      color: #0A0A0F;
    }
    
    .compliance-btn.primary:hover {
      transform: translateY(-2px);
      box-shadow: 0 8px 24px rgba(201, 169, 110, 0.3);
    }
    
    .compliance-btn.secondary {
      background: transparent;
      border: 1px solid #7A7572;
      color: #7A7572;
    }
    
    .compliance-btn.secondary:hover {
      border-color: #E8E4DF;
      color: #E8E4DF;
    }
    
    .compliance-footer {
      margin-top: 20px;
      text-align: center;
      font-size: 0.8rem;
      color: #7A7572;
    }
    
    .compliance-footer a {
      color: #C9A96E;
      text-decoration: none;
    }
    
    .compliance-footer a:hover {
      text-decoration: underline;
    }
    
    .close-btn {
      position: absolute;
      top: 16px;
      right: 16px;
      background: none;
      border: none;
      color: #7A7572;
      font-size: 24px;
      cursor: pointer;
    }
    
    .close-btn:hover {
      color: #E8E4DF;
    }
    
    /* Privacy Modal */
    .privacy-body {
      max-height: 60vh;
      overflow-y: auto;
      margin-bottom: 24px;
    }
    
    .privacy-section {
      margin-bottom: 24px;
    }
    
    .privacy-section h3 {
      font-family: 'Cinzel', serif;
      font-size: 1rem;
      color: #C9A96E;
      margin-bottom: 8px;
    }
    
    .privacy-section p {
      font-size: 0.9rem;
      color: #7A7572;
      line-height: 1.6;
    }
    
    .data-security {
      background: rgba(91, 140, 90, 0.1);
      border-radius: 12px;
      padding: 16px;
      margin-top: 16px;
    }
    
    /* Payment Modal */
    .payment-section {
      margin-bottom: 24px;
    }
    
    .payment-section h3 {
      font-family: 'Cinzel', serif;
      font-size: 1rem;
      color: #C9A96E;
      margin-bottom: 16px;
    }
    
    .packages-grid {
      display: grid;
      grid-template-columns: repeat(3, 1fr);
      gap: 12px;
    }
    
    .package-card {
      background: #0A0A0F;
      border: 1px solid #7A7572;
      border-radius: 12px;
      padding: 16px;
      text-align: center;
      position: relative;
    }
    
    .package-card.popular {
      border-color: #C9A96E;
    }
    
    .popular-badge {
      position: absolute;
      top: -10px;
      left: 50%;
      transform: translateX(-50%);
      background: #C9A96E;
      color: #0A0A0F;
      font-size: 0.7rem;
      padding: 4px 12px;
      border-radius: 12px;
    }
    
    .package-name {
      font-family: 'Cinzel', serif;
      color: #E8E4DF;
      margin-bottom: 8px;
    }
    
    .package-credits {
      font-size: 0.9rem;
      color: #8B5CF6;
      margin-bottom: 4px;
    }
    
    .package-price {
      font-size: 1.1rem;
      color: #C9A96E;
      font-weight: bold;
    }
    
    .package-per-credit {
      font-size: 0.75rem;
      color: #7A7572;
    }
    
    .subscription-card {
      background: linear-gradient(135deg, rgba(139, 92, 246, 0.2), rgba(139, 92, 246, 0.1));
      border: 1px solid #8B5CF6;
      border-radius: 12px;
      padding: 20px;
    }
    
    .subscription-header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      margin-bottom: 12px;
    }
    
    .sub-name {
      font-family: 'Cinzel', serif;
      color: #E8E4DF;
    }
    
    .sub-price {
      color: #8B5CF6;
      font-weight: bold;
    }
    
    .sub-features {
      list-style: none;
      padding: 0;
      margin: 0;
    }
    
    .sub-features li {
      color: #7A7572;
      font-size: 0.9rem;
      padding: 4px 0;
    }
    
    .refund-text {
      font-size: 0.85rem;
      color: #7A7572;
      line-height: 1.6;
      white-space: pre-line;
    }
    
    /* Age Modal */
    .age-text {
      text-align: center;
      margin-bottom: 24px;
    }
    
    .age-text p {
      font-size: 1rem;
      color: #E8E4DF;
      margin-bottom: 12px;
    }
    
    .age-warning {
      color: #C45B3E !important;
      font-size: 0.9rem !important;
    }
  `;
  
  document.head.appendChild(styles);
}

// ==================== 导出 ====================

if (typeof window !== 'undefined') {
  window.Compliance = {
    showDisclaimerModal,
    showPrivacyPolicy,
    showPaymentInfo,
    showAgeConfirmation,
    checkDisclaimerRequired,
    getComplianceInfo,
    COMPLIANCE_TEXTS
  };
}

console.log('✅ Compliance Module loaded - Google Play合规模块已加载');
